var scourText = "\"This is the scour bridge now, The Travellers put the name on it and its the scour bridge now, there was a house back down there thats gone now that used to own that garden, That was a big wide road there was wagons trailers, and tents, that ditch was miles back.\" <i>Biddy Collins</i> <br><br> \"We’d get a tube, the tube out of a car, get a rope and tie the tube, put the tube across us go across that bridge throw across the rope and get someone to drags us back across the water. We’d pedal up and down that canal and we’d get the children to pedal up and down.\" <i>Bridgie Collins</i><br><br>\"Dick and Paddy Dooley (Doon) they lived down here at scour bridge, the sister put the two of them out of the house and they bought a wagon and they had it for years and years.\" <i>James Collins</i>";

var pinkeenText = "\"That side of the road was all flat along and the wagons would park in longways with the forks facing up the way so when you light the fire you could sit in the mouth of the wagon or the tent and warm up. So each person had their tent or their wagon facing each other with the fire in between. The side of the road was completely flat theres hills there now, they did that in the 70’s or 80’s purposfully to stop the Travellers from pulling in.to camp, so this is how the block of cement for the bottom of the pump isint there, ya wont find it cause its covered.\" <i>Hughie Collins</i><br><br>\"Theyd pull there cause of the wind and that, on both sides ya had the big ditch and it would block the wind from coming in on top of ya. What they used to do and I remember it very clearly, theyd watch for the farmer, there was a farmer down here I think it was the left or the right and he used to come that way and he used to carry the milk, me granny old Biddy would come out with a burner that they made of copper, the farmer would get out and the fresh milk hed pour it in and fill it for her. The freshest of milk.\" <i>Hughie Collins</i><br><br>\"I remember bringing me father here 25 years ago and the pump was there and the base was there, then I was back me and my wife about 10 or 12 years ago the pump was gone but the base was there.<br>And believe it or not there was a way out to that field and I remember me grandfather he’d tie the horses feet with a piece of rag to stop em going anywhere, so no matter how long he left them they’d only be at the far side of the field. Spancil the pony they used to say.</br>The dump was up there Biddy up there on the left hand side, the local people would throw their rubbish and we used to go up and root for what ever we could find.\" <i>Hughie Collins</i><br><br>\"We used to stop at this camp years ago and we used to call it The Pinkeen road, and it was a grand camp, it wasn’t like it is now but it was real wide and we used put the tent in there, and the oul wagon and we hadn’t a wagon and if you had a wagon at that time you were rich. It was a nice time and it was homely and the people was grand. You’d see an odd guard come down on the bike and he’d stop for a few minutes and go on again. They wouldn’t bother ya that time they bother ya if ya put the oul pony out in a field and the farmer would get the guards and you’d have to leave, and that would only be a very odd time.\" <i>Biddy Collins</i><br></br>\"The pump is gone the pump was there and the pump is gone, or someone took the pump that was where we used to get the water in the pump. We’ll go in the name of the lord.\" <i>Biddy Collins</i>";


var woodyCrossText = "\"That house up there you would go to draw the milk, they’d give out the milk. There was four sisters living in there, they never got married, oh they were very very very nice, we’d get the milk there in the morning she’d tell ya ‘come now when the cows are milked and you’ll get milk’, and she would give you a big yoke of dripping. There’s two ways of going into that house one down there and you arrive at the back door and this would bring you to the front door, that would be for the gentry.<br>35 years since I was here, there was a little stream kind of a well down behind the bank and you’d get the spring water or even that you’d go back up there and there was a big pump on the right hand side. That time you’d love to stop along this road, we used to stay her for a month more or less, The men would be out bottoming the oul buckets and things and the women would be halking and trading, for food and things. There wouldn’t be harm done to you. I stayed here with me family and then we got married and we stayed here and we’d walk back into Edenderry to go to the pictures.\"<i>Bridgie Collins</i><br><br>\"James and oul Tom had an awful fashion of writing their names on the camps ya know, on the trees, did ya find the bird, there’s the bird on that tree.\" <i>Bridgie Collins</i>";

var bullsbridgeText = "\"Id say meself this is one of the ould bridges so I’d say meself this is where they did the eel fishing, see that black water that type of brown’e water you’d ketch pike that size in there Pike lives in dark water.\" <i>Martin Collins</i><br><br>\"Molly reckons on both sides of the bridge they’d pull in here and up on the left hand side and nearly a mile up that way, they all only had tents and four wheelers so it wouldn’t take much space to put a tent, it would be no more than a meter a meter and a half wide so you wouldn’t be looking for much there.\" <i>Hughie Collins</i><br><br>\"1958 since I was on the Bullsbridge, We used to get the water in in there to wash the clothes.\" <i>Molly Collins</i>";

var nineMileText = "\"This is the 9 mile road from Edenderry to Rathangan and we used to stay along here many years ago and we used to work in the bog, we’d call it footing turf. Where all the Travellers used to foot the turf in the bog. And we used to stay along here on down there one place or another there was no trailers that time only wagons.\" <i>Biddy Collins</i>";

var philsRoadText = "\"Phil’s road, the Travellers put the name on it on account of a fella from the road, he wasn’t that well kind of special and he used to go with two hand bags doing shopping, his name was Phil and the Travellers put Phil from Kinnegad on the camp.\" <i>James Collins</i>";

var jonestownXText = "\"We were reared around these roads, we used to hunt that land. We were reared off the land, do you see all around here well we were known as good as a begging ass around here.\" <i>James Collins</i>";


var midgeRiverText = "\"There could be 20 families down stopping here footing turf in the bog, that was a big wide camp went down the whole way, There’s a river down there at the bottom of the tree. Believe it or not we used to get eels in that river it’s a very small river but it’s very deep.\" <i>James Collins</i>";


var fanHillText = "\"Fan Hill was a very nice camp an’ the people knew us real well like, around it. A real good camp an’ a good ould field out for the horses.\" <i>Paddy McDonagh</i>";


var tubberdalyText = "\"Take a walk around Tubberdaly, in the summer time of the year, old <i>Paddy McDonagh</i> would be along here and me Daddy would be along here and old Biddy would be here in the middle. I had me tent over there, across the road, see that flat stone that’s where my fire was and me tent was there.<br>Ya see that river there, that was a lovely clean spring river and there was a thing there they used to call watergrass and old Biddy used to get it, well now she used to boil it along with a bit of old bacon and it was lovely. And there was a little waterfall along there its gone now I don/t hear the water running over it anyway but you know at night time it would put you to sleep.\" <i>James Collins</i><br><br>\"If you come here at summer time, you see that yoke there its like bamboo cane, that was never there, it was pure level, a lovely green corner, lovely green grass on it. There’s rocks there now and yokes that must have grew and they must have dumbed that there, in behind that wall there’s oul bottles belonging to us, oul shoes, ould bits of irons and rubbers according to when we was building a wagon here and he’d throw the yokes in over the wall.<br>Its a long time since me and Mingo came over that wall there, me and him, wed get the sticks out of that wood, The low part of the wall, we used to gather the sticks in there and then when we was free, when the sticks was got and the water was got and then we were free for the day and we got our fishing rods and we’d go miles along that canal fishing pike, both ways we’d go on that way one evening and then we’d start there and go back over to the village of Rode nearly fishing as well. That’s the grand canal.\" <i>James Collins</i><br><br>\"There’s more oul names on them trees in them woods there. Tubberdaly bridge, we used to lie on our bellies and catch eels in under that bridge.\" <i>James Collins</i><br><br>\"I’ll show you where we put our names, I cut it into the stone but. Mingo put it on with red paint and I came back here a few years ago and the red paint was nearly gone off it and I put black paint over the letters the ways I could find it at Tubber Daly.\" <i>James Collins</i>";


var headTubberText = "\"The head of Tobber Daly we were camped there during the 1961 all Ireland final, between Down and Offaly the first all-Ireland final Offaly ever played. Down bet them by one point and the referee fiddled Offaly out of a penalty, there was talk for over 12 months after about what the referee done. The battery went flat of the old time wireless and we ran on to that cottage, that man had an electric wireless that you could hear back on the road I’ll never forget that till the day I die.\" <i>James Collins</i>";


var greenRoadText = "\"That time there was hardly any motor cars and the road was only the width of the car anyway, that time we used to stop there and the horses would be walking up and down there with no motorcars and there’s a house up there called Edgels and he gave us land up there for the three horses. He came up and told us we could put the horses below in the field and if they are ploughing them he says I’ ll come up and tell ye to take them out.\" <i>James Collins</i>";

var faheysHillText = "\"The camps was all there now, that was a handball alley we used to play in there. This was Faheys hill, that was an open handball alley. The Smiths used to go in there Hughie and Monnie Smith we were stopping around Edenderry with them.\" <i>James Collins</i>";


var andysRdText = "\"Where this gate is this was a corner, the whole road down was called Andy’s road that’s what the Travellers called it. There was a well up further now but they done away with it now.\" <i>James Collins</i>";


var birdysHouseText = "\"This is Birdy’s Big house, that’s the name they put on it, the man’s name was Bermingham they owned all that land.\" <i>James Collins</i><br><br>\"We came down here about 20 year ago, Podge and Qughie, theres great land down here we used to always hunt it we used to camp along it, we were gone for hours through the fields, so we headed back, there was a motor car parked at the gate, the man got out when he seen us coming he opened the boot and took out a double barrel shot gun, he put his hand in his pocket and pulled out two cartridges and put them into it. So we came to the gate, he says ‘what are ye doin in there’ we said sir were causing no harm, cause we used to always hunt that ground. You did he says, yees we said, we used to camp along there right at the gate, well he started staring at us and he caught the gun, and he broke it in half, and took the bullets out and put them back down into his pocket, and put the gun back into the car. You don’t come on and tell me he says, that ye’re the young fellas that used to play the marbles in that road, and ye used to help me with me cattle, bringing them by the camp.<br>Now the reason why he says do you see that house he says that’s me fathers house and its been broken into several times, Podge says we didn’t do that, I know ye didn’t he says, I know bloody well ye didn’t do it he says, he says I know who ye are now and any time ye want to hunt that land ye come back and do it. I swear on the blessed lady.\" <i>James Collins</i>";


var jimHillsText = "\"Up here is a camp called Jim Hills, we used to camp in along off the road, and we’d climb that gate and head out over hunting them fields, hares and rabbits, and that house further up there is where Jim Hill used to live.\" <i>James Collins</i>";


var judgeText = "\"This road is called Judge Weightlees, we used to camp down here at the other end of this road, In in the back of them houses the oul yard houses they used to call them and there was a judge lived in it. This was a whole camping road.\" <i>James Collins</i>";


var berrigansText = "\"Berrigans corner is a big wide corner and the council made a big yard out of it, and you have the green road here, that’s the real name now that’s not a Traveller name.\" <i>James Collins</i>";


var bluntsText = "\"Blunt’s corner off to the right after the green road, just down here on the right hand side. The people up there were called Blands, the Travellers couldn’t say it like that so they called it Blunts instead.\" <i>James Collins</i>";


var crinnonsText = "\"Captain Crinnon was the name of this camp, he was a captain of something anyway, that was the name that was on it. He had a brother a priest in Kinnegad, Father Crinnon was his name.\" <i>James Collins</i>";